remotes:
  github:
    aliases: [gh]
    url: git@github.com:${user}/${repo}.git
  codeberg:
    aliases: [cb]
    url: git@codeberg.org:${user}/${repo}.git
  sourcehut:
    aliases: [srht, sh]
    url: git@git.sr.ht:~${user}/${repo}

defaults:
  remotes: [github, codeberg, sourcehut]
  path_prefix: ~/Developer

repos:
  gemrest/windmark: {}

  gemrest/september:
    sourcehut:
      user: fuwn

  fuwn/dotfiles:
    path: ~/.dotfiles

  fuwn/private-project:
    remotes: [github]

  fuwn/fork:
    github: git@github.com:upstream/original.git
